Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.provision "shell", inline: <<-SHELL
    echo "Using greeter plugin!"
  SHELL

  # Your plugin can also be called via CLI later
end
