Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.hostname = "vagrant-kvm-vm"
  config.vm.network "private_network",
    ip: "192.168.100.10", 
    libvirt_network_name: "vagrant_kvm_network"
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 2048
    libvirt.cpus = 2
    libvirt.driver = "qemu"
    libvirt.machine_type = "pc"
    libvirt.storage_pool_name = "default"
  end
end