Vagrant.configure("2") do |config|
    # Box configuration
    config.vm.box = "ubuntu/bionic64"

    # Port forwarding
    config.vm.network "forwarded_port", guest: 80, host: 8080

    # Provisioners configuration
    config.vm.provision "shell", inline: <<-SHELL
        # Update package list and install Apache
        sudo apt-get update
        sudo apt-get install -y apache2
        sudo systemctl enable apache2
        sudo systemctl start apache2
        # Create the symbolic link for the website
        ln -fs /vagrant/html/ /var/www/html 
    SHELL
    
    config.vm.provision "shell", path: "provision.sh"
end
