# Create the Vagrantfile for the Multimachine clusters
# Create the web machine
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.define "web" do |web|
        web.vm.hostname = "web"
        web.vm.network "forwarded_port" , guest: 80, host: 8080
        web.vm.network "private_network", ip: "192.168.56.10"
        web.vm.provision "shell", path: "web_provisioner.sh"
        web.vm.provision "shell", inline: "sudo apt-get install -y mysql-client"
    end 

# Create the db machine
    config.vm.define "db" do |db|
        db.vm.hostname = "db"
        db.vm.network "private_network", ip: "192.168.56.11"
        db.vm.provision "shell", path: "db_provisioner.sh"
    end 
end 